### PR TITLE
Right aligned inline radio buttons

### PR DESCRIPTION
**Pull request by hashitha**

### CODE REVIEW

**Comment by hashitha** [comment]
Fix for alignments
  ```
<row>
    <col
      width="2">
      <text>Do you have any allergies?</text>
    </col>
    <col
      width="1">
      <select
        name="AnyAllergies"
        as="radiobuttonsinline">
        <option
          value="No">No</option>
        <option
          value="Yes">Yes</option>
      </select>
    </col>
  </row>
```

image

**Comment by edongashi** [comment]
Could we maybe use [LinePosition](https://github.com/WPF-Forge/Forge.Forms/blob/f69cab0a03b7d923e0a4607d892f48891d295873/Forge.Forms/src/Forge.Forms/Annotations/FormContentAttribute.cs#L81) or some other alignment property for this? I mean somehow figure the alignment from a reusable property. If not then I'll cleanup the XAML a little and merge.

**Comment by hashitha** [comment]
If you add a LinePosition does it align to right?

**Comment by edongashi** [comment]
I was wrong, it's for inline elements and unrelated to this. We can merge this considering I don't see another way to describe alignment.

**Comment by redbaty** [comment]
Any reason why this is still not merged @edongashi ?

**Comment by edongashi** [comment]
I thought maybe we can refactor this without duplicating the entire template, something like a trigger inside the regular inline template that sets alignment=right when the selectiontype is right aligned. No big deal though, we can merge it and refactor later.

**Pull request merged**
