### PR TITLE
Fix window focus/keyboard focus when showing windows

### PR DESCRIPTION
**Pull request by aalex675**
window.ShowDialog is blocking so window.Activate..., etc... doesn't get called until window is closed)

### CODE REVIEW

**Review by edongashi — APPROVED** [review]
Makes sense. Thank you!

**Comment by edongashi** [comment]
I need to update nuget keys and check out how to do a prerelease, which will also include your change.

**Comment by aalex675** [comment]
Hey Edon, Have you had a chance to work through the nuget keys issue to get this build released?

**Comment by edongashi** [comment]
Hello @aalex675, sorry, I should have informed you! `1.2.0-beta3` is already live on NuGet. I chose to make a prerelease because of the XAML packages updates. That's why you may have not seen it in your editor. Please check it out and let me know if you have any issues.

**Pull request merged**
