### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by edongashi**

### CODE REVIEW

**Comment by edongashi** [comment]
@ChezzPlaya @BenjaminSieg I have merged both of your changes in this PR.

Please let me know if it looks alright. I haven't touched WPF stuff in ages.

**Comment by ChezzPlaya** [comment]
Looks good to me!

**Review by ChezzPlaya — APPROVED** [review]

**Comment by BenjaminSieg** [comment]
Should be good, yes!
Thanks!

**Review by BenjaminSieg — APPROVED** [review]

**Review by BenjaminSieg — APPROVED** [review]

**Comment by edongashi** [comment]
Thank you! We'll start with a pre-release version to see if it works as intended.

**Pull request merged**
